### ISSUE TITLE
/pnc event create

### ISSUE THREAD

**Issue by Nalkos** [corentingosselin/ProdigyNightclubWiki#1]
Hello when I do : /pnc event create mynightclub test &6Test 05/05/2021 20:00:00 05/05/2021 21:00:00 1000 100     as indicated in the wiki, it tells me that there is an error: Error: 21:00:00 must be a number

So either I know I'm wrong or there's a problem. 
Thank you

(sorry for my english I use a translator)

**Comment by corentingosselin** [comment]
Bonjour,

Cette erreur s'affiche car vous exécutez la commande à l'intérieur de la boite de nuit:
La commande correcte est:
`/pnc event create test &6Test 05/05/2021 20:00:00 05/05/2021 21:00:00 1000 100`
Si vous êtes à l'extérieur vous devez préciser le nom du nightclub

Hello,

You are getting this error because the command is executed inside the nightclub:
The right command is:
`/pnc event create test &6Test 05/05/2021 20:00:00 05/05/2021 21:00:00 1000 100`
If you are outside the nightclub you must specify the nightclub name
