### ISSUE TITLE
Error when I try to run majority of commands

### ISSUE THREAD

**Issue by BurnhamR** [corentingosselin/ProdigyNightclubWiki#12]
I'm getting this error with the plugin. This error is common and happens with most of the commands I run, and says in chat:
![image](https://user-images.githubusercontent.com/58826382/135412756-5fa3e842-9e44-4e51-b064-2facc60518a9.png)

https://pastebin.com/x61BP79S

Server:
Paper Spigot 1.16.5 788
Plugin version: 3.0.63
Plugins:
Skript, World Edit, PlaceholderAPI, ProtocolLib, ViaBackwards, ViaVersion, Ersatz, Prodigy Nightclub

-- Update --

After doing some troubleshooting,

That error is caused by upgrading to Java 16. Error is present on both Spigot and Paper Spigot while using Java 16.
Downgrading to Java 11 or 8 Fixes the issue but presents me with a new issue

This is the new error after downgrading Java(11,8), the error appears on the latest Paper Spigot and Spigot.
https://pastebin.com/yUnFZvcA
Same plugins/plugin versions as before
Same error in chat
Different error in console.

== Edit 2 ==

Trying 1.17.1 Spigot with Java 16 and the latest release of PNC cause the error as well
https://pastebin.com/shBKCgBA

**Comment by corentingosselin** [comment]
When you are executing this command, are you inside the nightclub ?
If yes are you sure the nightclub is really created ?

**Comment by BurnhamR** [comment]
Yes I am in the nightclub and the nightclub is in the files, so I assume it's really created. 
Even after restarts, it happens.

I may be wrong, but I believe the issue is if a chunk/entity for the nightclub is unloaded, it happens.

**Comment by corentingosselin** [comment]
> I may be wrong, but I believe the issue is if a chunk/entity for the nightclub is unloaded, it happens.

Impossible, prodigynightclub does not create any real entity, only via packet so it could not be a chunk related issue because those entities are spawned when you enter inside the nightclub.

If they do not spawn it simply means there is no nightclub.
1 possibility reason is that you have an error configuration file and when you start your server prodigynighclub is throwing an error and the nightclub is not loaded.

You can execute /pnc nightclub list to check if the nightclub is correctly loaded
